---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1ry5rju8naz9428c9kxa9f374vdws8amnr90grsfnthtq8mkvnuxslysm0m
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1ry5rju8naz9428c9kxa9f374vdws8amnr90grsfnthtq8mkvnuxslysm0m
