# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:+40k7TKTTgJE+5M5tNL7wgiAuj0Lccw5p061RkPZQiudte4/JrAw/h0gb2/+4cjKWwUikLzecQ6pFfV2oT9eY4s7/FXtTdoaRpSO4VYlBcsygAN+Ng4TXeJb68hFojf7ngTB87cyZaAa5lWrveBlN56acPHjwPtXGnc1yR7jjL6IvO9avB8hytgoTvFIy+a7i9G8H/u1+gfe/f1eNaW6Fo2JeR7k61EbF0lsi+k=,iv:5ZE7YdJu+d5uxzwpUAPDC4G0mQyihB7FDe3+Paw5VxE=,tag:BNb9J9tTYAdA/V4AVf1CSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ry5rju8naz9428c9kxa9f374vdws8amnr90grsfnthtq8mkvnuxslysm0m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwd1ZzUWpDYzcvNzA2ZTFH
            c1l4MGRjM2lPaGpRN2Y0V3ZhSCtKY21OUTJZClVOYnltdFkzUzZTdWxQaElzaWoy
            ajRCQ3hxcEdaU3RLN0dZSTFGU2J0d28KLS0tIDczcTRlTFdPSWFqVzB5dDFpUW5w
            WjQ3andKTmdNdm4xVmx1djk1MENCb2sKXvYqz7MSf/kHs5N8ZUqsm8nu56zP8eQr
            Iie0V4pfCSGvXkljfdYhH/Pn/ypGkSxN+iR2/0Fm0x6L8woprCpy4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T10:59:09Z"
    mac: ENC[AES256_GCM,data:tnjUx9oWdmYi74RwFB4Bniu+T0XJ9oyNvU3ItEoMDfFLIlTOl3upVDN7IKFIfKhjVxBjFrsG/HLm2ExvL1kE19dOTvjhcjRFk1I9UCy7rKdRG3HX/ueAUejZ5lLIF+aJMkiOq0dVUsMnSNM9kH1IkfyLuaZzW4aS4RVP2GT2Rb8=,iv:EpmFbZ7nnSXH/s6Gi4Myw+6ey8861ynbTG4WuCwIPcM=,tag:o5H0asDMelwCgBfE156R8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
