# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: |-
        type: s3
        config:
          bucket: "thanos"
          endpoint: "minio.tools.svc:9000"
          access_key: "${SECRET_MINIO_ACCESS_KEY}"
          secret_key: "${SECRET_MINIO_SECRET_KEY}"
          insecure: true