---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.fairwinds.com/stable
      chart: goldilocks
      version: 4.0.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 5m
  values:
    dashboard:
      enabled: true
      replicaCount: 1
      ingress:
         enabled: true
         ingressClassName: "nginx"
         hosts:
           - host: "goldilocks.${SECRET_DOMAIN}"
             paths:
                path: /
         tls:
           - hosts:
              - "goldilocks.${SECRET_DOMAIN}"
