---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.min.io/
      chart: minio
      version: 3.3.4
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2021-10-08T23-58-24Z
      pullPolicy: IfNotPresent
    mcImage:
      repository: quay.io/minio/mc
      tag: RELEASE.2021-09-23T05-44-03Z
      pullPolicy: IfNotPresent
    helmKubectlJqImage:
      repository: bskim45/helm-kubectl-jq
      tag: 3.1.0
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
    service:
      type: ClusterIP
      clusterIP: ~
      port: 9000
    existingSecret: minio-helm-values
    ingress:
      enabled: false
      ingressClassName: "nginx"
      hosts:
        - "minio.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "minio.${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    securityContext:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: true
    nasgateway:
      enabled: false
      # Number of parallel instances
      replicas: 3
    buckets:
      - name: loki
        policy: none
        purge: false
      - name: thanos
        policy: none
        purge: false
        #  valuesFrom:
        #    - kind: Secret
        #      name: "minio-helm-values"
        #      optional: false
