# yamllint disable
# apiVersion: v1
# kind: Secret
# metadata:
#     name: minio-helm-values
#     namespace: tools
# type: Opaque
# stringData:
#     MINIO_ROOT_PASSWORD:
#     MINIO_ROOT_USER:
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: tools
type: Opaque
stringData:
        MINIO_ROOT_USER: ${SECRET_MINIO_ACCESS_KEY}
        MINIO_ROOT_PASSWORD: ${SECRET_MINIO_SECRET_KEY}