# yamllint disable
# apiVersion: v1
# kind: Secret
# metadata:
#     name: minio-helm-values
#     namespace: tools
# type: Opaque
# stringData:
#     values.yaml: |
#         accessKey:
#         secretKey:
apiVersion: v1
kind: Secret
metadata:
    name: minio-helm-values
    namespace: tools
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:XqLvV9Nm2PQnmMEU2F9g8Hm+6qtKgGP1eqA=,iv:IAoa5IuCyYGZAhWNNxaQcomCKmSItuyiP3Qmj5C6Pu0=,tag:Az9nEIV+N0y1zivSxVlSXQ==,type:str]
    rootPassword: ENC[AES256_GCM,data:UV3l1R6JWfDLPBBrf+UxDOw/Ii5CL/KgE6g=,iv:JCr5hOt2saXq/EtPjiun+iof0JyKB0hpJfh37A914LQ=,tag:4cP8qrXcWNiNB/E30idp5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ry5rju8naz9428c9kxa9f374vdws8amnr90grsfnthtq8mkvnuxslysm0m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUIxSTdjbm1aaWpuam92
            VTZNSWdxTlZjOXlyMmRvWGRwd2JrNWUzZ3g4Ci9HUUh1b1hIRTFwMUNMbnRqdVdN
            a2xDWE02Z3dJeUMyaDQvT1NqZTQyS28KLS0tIGRydlVHdDlyMUc1WS9QVG9HaHZP
            OWRMT0ZiaDJSWm9qcUpjc3JlQ29SZTQKiel9yRERl9yKUdbdLLFkmg2joKgB4wqx
            CwPqbyz9MBIkhaGyQ8WoewXPqeOatYOKnzIc4AyGcJ2JJB89b/QaIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T10:59:09Z"
    mac: ENC[AES256_GCM,data:Ay2QLg7dQ/rBtJ+6xdObApz8JGe2ayx0zjGr5zgD5YUBluORspqgvc9/iC486TvyxxaplR/llqHTbtgc95ODkog2kRLV+R9R/Gkkfje9BmwtX1qDQYP4rzwtTW+mnk+8DSy/F58dU1DdcE3/SmMdrvxQoBTGoX8/qOC2qg2e6Ck=,iv:QRyJtHBSckTnrioR4N33urIcelTFLd6gFWpR8Cc1OmU=,tag:B+XF+3qVBTkR6ykCH8EjVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
