# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ${SECRET_DOMAIN}
  SECRET_GRAFANA_PASSWORD: ${SECRET_GRAFANA_PASSWORD}
  SECRET_MINIO_ACCESS_KEY: ${SECRET_MINIO_ACCESS_KEY}
  SECRET_MINIO_SECRET_KEY: ${SECRET_MINIO_SECRET_KEY}
  SECRET_UPTIMEROBOT_API_KEY: ${SECRET_UPTIMEROBOT_API_KEY}
  SECRET_ALERT_MANAGER_SLACK_WEBHOOK: ${SECRET_ALERT_MANAGER_SLACK_WEBHOOK}
  SECRET_SLACK_API_TOKEN: ${SECRET_SLACK_API_TOKEN}
  UPTIMEROBOT_HEARTBEAT_URL: ${UPTIMEROBOT_HEARTBEAT_URL}
  