# yamllint disable
# comm_config.yaml: |
#     communications:
#         discord:
#             enabled: true
#             notiftype: short
#             token:
#             botid:
#             channel:
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: |
        communications:             
          slack:
            enabled: true
            channel: k8s-events
            token: ${BOTKUBE_SECRET_SLACK_API_TOKEN}
            notiftype: short