# yamllint disable
# comm_config.yaml: |
#     communications:
#         discord:
#             enabled: true
#             notiftype: short
#             token:
#             botid:
#             channel:
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:fBYZRcEzPOKJqkQ6eWP8ieXkvIP+Xp7riyrrpbcMF45lJ2sYbDnz9rBp8YtW+j9Nhti6pRZIPEjsl6var2WktN1qkBSQOEW7uvfxLyk/1st3SOcNziHA4nyFZS332dT3631Cb435CJUKaW/oeu/zMIH3Zw8EpWi70Y5rpIsEcQNCIFDyEbbfnUpWDY1W/juP2Q==,iv:Yk5zGxSIkIYqQJeK9IdOi5tE9LSQjx7ZQ+wl1Z8Bj8s=,tag:jmmE6HHsCQRSJAhoxk3TWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ry5rju8naz9428c9kxa9f374vdws8amnr90grsfnthtq8mkvnuxslysm0m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUkYrS2ZDMlRlL3MxNU10
            VDBCQjM1MFZ1L042YnNBNVZVSzhsaTByMWpZCmlKait5ODM1TmpmSDV6eENucmZ4
            ZDRzMmUyVHU0eERRem9nVWVRRmtpU0UKLS0tIFc0VHo5YjFqMXZMRC8ySmR5ZkNw
            OVRFdjdVOVgwZFg0YzhaQ3ZvUlQyUGcKDsNV5U2brU+VcVy2dcI7qg/v/ZHi8Iu7
            6GO96tQPW6UyV2wZQD5N2cKn+DZPe5G69BXEbpKRuQzNHOvOYRaIHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-25T10:59:09Z"
    mac: ENC[AES256_GCM,data:g388EnWvzo+JoS1bU2sYw3JOToh/5lxSKrP69EJVO/nvyESGKDtp3Nz5ESECCcK95bhnd1xNomquknl9gRHKpryZEY9PiZlqDwHi4IoL2+ZUZztpJyNxaVrPCBAjf9q47ZjlvYcM221ByX7WhmtwnEeYVoPGoBFTD8MwM3shYhs=,iv:WcHA05EUYkbVCW1PIskqdiV5NZwQml2x4Dcs+usFO74=,tag:Y9xIPq1Bdnx15lTUjvvDbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
